def get_checklist_template(package):
    templates = {
        "Flow Conditioner - 1100": [
            "Integridade da estrutura principal?",
            "Conexões flangeadas apertadas?",
            "Placas perfuradas/condicionadoras em bom estado?",
            "Identificação (TAG) legível?",
            "Sem sinais de corrosão ou danos mecânicos?",
            "Limpeza interna adequada?",
            "Documentação técnica disponível e conforme?",
        ],
        "Zanker - 1150": [
            "Estado geral do equipamento?",
            "Funcionamento de partes móveis (se aplicável)?",
            "Conexões seguras?",
            "Nível de ruído/vibração normal?",
            "Lubrificação adequada (se houver)?",
            "Proteção contra intempéries?",
            "Placa de identificação legível?",
        ],
        "Strainers - 1200": [
            "Corpo do filtro sem corrosão?",
            "Elemento filtrante limpo e em bom estado?",
            "Vedações íntegras?",
            "Purgador/dreno funcionando?",
            "Pressão diferencial dentro dos limites?",
            "Fixação segura?",
            "Acesso para manutenção desobstruído?",
        ],
        "Static Mixer - 1250": [
            "Integridade da carcaça?",
            "Elementos internos fixos?",
            "Sem sinais de vazamento?",
            "Identificação (TAG) presente?",
            "Conexões de processo apertadas?",
            "Sem obstruções visíveis?",
            "Certificado de material disponível?",
        ],
        "FCV - 1300": [
            "Condição geral do corpo da válvula?",
            "Atuador (pneumático/elétrico) em bom estado?",
            "Conexões seguras e sem vazamentos?",
            "Posicionador funcionando corretamente (se aplicável)?",
            "Sinal de controle recebido e respondido?",
            "Gaxeta sem vazamentos?",
            "Curso da válvula completo?",
        ],
        "Gate Valves - 1350": [
            "Volante/atuador em boas condições?",
            "Gaxeta sem vazamentos?",
            "Corpo da válvula sem danos?",
            "Indicador de posição funcionando (se aplicável)?",
            "Operação suave (abrir/fechar)?",
            "Flanges alinhadas?",
            "Parafusos e porcas apertados?",
        ],
        "Small Ball Valves - 1400": [
            "Alavanca/atuador funcionando suavemente?",
            "Vedações sem vazamentos?",
            "Corpo da válvula íntegro?",
            "Identificação (TAG) visível?",
            "Operação completa (abrir/fechar)?",
            "Sem sinais de corrosão?",
            "Instalação correta?",
        ],
        "Big Ball Valves - 1500": [
            "Condição geral do corpo?",
            "Sistema de acionamento (se houver) funcionando?",
            "Gaxetas e vedações em bom estado?",
            "Indicador de posição correto?",
            "Operação suave e completa?",
            "Conexões flangeadas sem vazamentos?",
            "Lubrificação do atuador (se aplicável)?",
        ],
        "Plug Valves - 1600": [
            "Operação da chave/atuador suave?",
            "Vazamentos na gaxeta/corpo?",
            "Lubrificação adequada (se aplicável)?",
            "Identificação (TAG) legível?",
            "Sem obstruções no fluxo?",
            "Conexões de processo apertadas?",
            "Limpeza externa?",
        ],
        "TRV / PSV - 1700": [
            "Condição geral da válvula?",
            "Lacre de segurança intacto?",
            "Sem sinais de corrosão ou danos?",
            "Identificação (TAG) clara?",
            "Bocal de entrada e saída desobstruídos?",
            "Dreno funcionando (se houver)?",
            "Certificado de calibração disponível?",
        ],
        "DBB Valves - 1800": [
            "Operação das duas válvulas independente?",
            "Vedações sem vazamentos?",
            "Purgador/vent funcionando?",
            "Identificação (TAG) presente?",
            "Flanges alinhadas?",
            "Parafusos e porcas apertados?",
            "Sem sinais de corrosão?",
        ],
        "Others - 1900": [
            "Condição geral do equipamento?",
            "Função principal operacional?",
            "Conexões seguras?",
            "Identificação (TAG) visível?",
            "Documentação disponível?",
            "Acesso para manutenção?",
            "Sem danos visíveis?",
        ],
        "Skid Fabric - 2100": [
            "Integridade estrutural da base?",
            "Pintura/revestimento em bom estado?",
            "Acessibilidade para manutenção?",
            "Identificação geral do skid?",
            "Nivelamento e fixação adequados?",
            "Passagem de cabos/tubulações organizada?",
            "Placa de identificação do skid?",
        ],
        "Meter Run Fabric - 2200": [
            "Integridade das tubulações?",
            "Suportes adequados?",
            "Conexões flangeadas apertadas?",
            "Identificação do trecho de medição?",
            "Sem sinais de corrosão ou vazamentos?",
            "Alinhamento do conjunto?",
            "Acesso para instrumentação?",
        ],
        "Structure Material - 2300": [
            "Condição geral do material (corrosão, deformação)?",
            "Fixações seguras?",
            "Pintura/revestimento protetor?",
            "Identificação do material (se aplicável)?",
            "Sem danos estruturais?",
            "Conformidade com desenhos?",
            "Certificados de material disponíveis?",
        ],
        "Piping Material - 2400": [
            "Integridade das tubulações (corrosão, amassados)?",
            "Suportes adequados?",
            "Identificação da linha/material?",
            "Isolamento térmico em bom estado (se aplicável)?",
            "Sem sinais de vazamento?",
            "Alinhamento e caimento corretos?",
            "Conformidade com especificações?",
        ],
        "Stud Bolts - 2500": [
            "Rosca em boas condições?",
            "Sem sinais de corrosão excessiva?",
            "Dimensões conforme especificação (amostragem)?",
            "Certificado de qualidade disponível (se requerido)?",
            "Material correto?",
            "Embalagem original (se novo)?",
            "Quantidade conforme lista?",
        ],
        "Gasket - 2600": [
            "Tipo e dimensões conforme especificação?",
            "Armazenamento adequado (sem danos)?",
            "Data de validade (se aplicável)?",
            "Certificado de qualidade disponível (se requerido)?",
            "Material correto?",
            "Sem deformações ou cortes?",
            "Quantidade conforme lista?",
        ],
        "Others - 2900": [
            "Condição geral do material/componente?",
            "Conformidade com a especificação?",
            "Embalagem íntegra (se aplicável)?",
            "Identificação clara?",
            "Sem danos visíveis?",
            "Quantidade verificada?",
            "Documentação de fornecedor disponível?",
        ],
        "Turbine - 3100": [
            "Estado geral da carcaça?",
            "Conexões elétricas e de instrumentação seguras?",
            "Sem ruídos ou vibrações anormais?",
            "Identificação (TAG) legível?",
            "Lubrificação adequada?",
            "Acesso para manutenção?",
            "Certificado de calibração disponível?",
        ],
        "Coriolis - 3200": [
            "Integridade dos tubos de medição?",
            "Conexões elétricas e de sinal seguras?",
            "Sem vazamentos?",
            "Identificação (TAG) presente?",
            "Fixação segura?",
            "Sem obstruções no fluxo?",
            "Certificado de calibração disponível?",
        ],
        "PD Meter - 3300": [
            "Condição geral do medidor?",
            "Conexões de processo sem vazamentos?",
            "Leitura do totalizador coerente?",
            "Identificação (TAG) visível?",
            "Sem ruídos ou vibrações anormais?",
            "Lubrificação adequada?",
            "Certificado de calibração disponível?",
        ],
        "Ultrassonic - 3400": [
            "Transdutores em bom estado?",
            "Conexões elétricas e de sinal seguras?",
            "Sem obstruções na tubulação de medição?",
            "Identificação (TAG) legível?",
            "Acoplamento dos transdutores correto?",
            "Sem danos no cabo?",
            "Certificado de calibração disponível?",
        ],
        "Magnetic - 3500": [
            "Bobina e eletrodos em bom estado?",
            "Conexões elétricas e de sinal seguras?",
            "Tubulação de medição limpa?",
            "Identificação (TAG) presente?",
            "Aterramento correto?",
            "Sem sinais de corrosão?",
            "Certificado de calibração disponível?",
        ],
        "Prover - 3600": [
            "Integridade mecânica do prover?",
            "Conexões hidráulicas sem vazamentos?",
            "Sensores e instrumentação funcionando?",
            "Identificação (TAG) visível?",
            "Sistema de acionamento (pistão/esfera) funcionando?",
            "Vedações em bom estado?",
            "Certificado de calibração disponível?",
        ],
        "Auto Samp.  & Jet Mix- 3700": [
            "Condição geral do amostrador/misturador?",
            "Sistema de acionamento funcionando?",
            "Conexões seguras?",
            "Identificação (TAG) legível?",
            "Sem vazamentos?",
            "Limpeza interna adequada?",
            "Acesso para manutenção?",
        ],
        "Man Sampl Oil - 3800": [
            "Condição geral do sistema de amostragem?",
            "Válvulas de bloqueio funcionando?",
            "Recipientes de amostra adequados?",
            "Identificação (TAG) visível?",
            "Sem vazamentos?",
            "Acesso para coleta de amostra?",
            "Limpeza do sistema?",
        ],
        "Others - 3900": [
            "Condição geral do equipamento?",
            "Função principal operacional?",
            "Conexões seguras?",
            "Identificação (TAG) visível?",
            "Documentação disponível?",
            "Acesso para manutenção?",
            "Sem danos visíveis?",
        ],
        "Coriolis - 4100": [ # Repetido, assumindo que é para Gás, mas com foco similar ao de Óleo
            "Integridade dos tubos de medição?",
            "Conexões elétricas e de sinal seguras?",
            "Sem vazamentos?",
            "Identificação (TAG) presente?",
            "Fixação segura?",
            "Sem obstruções no fluxo?",
            "Certificado de calibração disponível?",
        ],
        "Flare - 4200": [
            "Integridade da ponta do flare?",
            "Sistema de ignição funcionando?",
            "Piloto aceso (se aplicável)?",
            "Sem obstruções na linha de flare?",
            "Suportes adequados?",
            "Acesso para inspeção?",
            "Identificação (TAG) visível?",
        ],
        "Orifice Carrier - 4300": [
            "Integridade do corpo do porta-placa?",
            "Vedações em bom estado?",
            "Conexões de tomada de pressão limpas?",
            "Identificação (TAG) legível?",
            "Sem sinais de corrosão?",
            "Acesso para troca da placa?",
            "Parafusos e porcas apertados?",
        ],
        "Cone - 4400": [
            "Integridade do cone de medição?",
            "Conexões de processo sem vazamentos?",
            "Tomadas de pressão limpas?",
            "Identificação (TAG) presente?",
            "Sem danos ou deformações?",
            "Acesso para inspeção?",
            "Certificado de material disponível?",
        ],
        "Ultrassonic - 4500": [ # Repetido, assumindo que é para Gás, mas com foco similar ao de Óleo
            "Transdutores em bom estado?",
            "Conexões elétricas e de sinal seguras?",
            "Sem obstruções na tubulação de medição?",
            "Identificação (TAG) legível?",
            "Acoplamento dos transdutores correto?",
            "Sem danos no cabo?",
            "Certificado de calibração disponível?",
        ],
        "Gas Chromatography - 4600": [
            "Condição geral do cromatógrafo?",
            "Conexões de gás de arraste e amostra seguras?",
            "Sistema de aquecimento/resfriamento funcionando?",
            "Identificação (TAG) visível?",
            "Gases de calibração disponíveis?",
            "Limpeza interna e externa?",
            "Acesso para manutenção?",
        ],
        "Man Sampl Gas - 4700": [
            "Condição geral do sistema de amostragem?",
            "Válvulas de bloqueio funcionando?",
            "Cilindros de amostra adequados?",
            "Identificação (TAG) visível?",
            "Sem vazamentos?",
            "Acesso para coleta de amostra?",
            "Limpeza do sistema?",
        ],
        "Others - 4900": [
            "Condição geral do equipamento?",
            "Função principal operacional?",
            "Conexões seguras?",
            "Identificação (TAG) visível?",
            "Documentação disponível?",
            "Acesso para manutenção?",
            "Sem danos visíveis?",
        ],
        "E&I Contractor - 5100": [
            "Escopo de trabalho definido?",
            "Equipe qualificada?",
            "Ferramentas e equipamentos adequados?",
            "Plano de segurança implementado?",
            "Documentação de projeto disponível?",
            "Cronograma de trabalho?",
            "Comunicação eficaz?",
        ],
        "E&I Engineering - 5200": [
            "Desenhos e diagramas atualizados?",
            "Especificações técnicas completas?",
            "Cálculos e dimensionamentos verificados?",
            "Conformidade com normas e padrões?",
            "Revisões de projeto concluídas?",
            "Documentação de engenharia organizada?",
            "Interface com outras disciplinas?",
        ],
        "Ex Inspection - 5300": [
            "Equipamento certificado Ex?",
            "Integridade da carcaça Ex?",
            "Aperto dos parafusos da tampa?",
            "Passagens de cabos seladas?",
            "Aterramento correto?",
            "Placa de identificação Ex legível?",
            "Sem sinais de danos ou modificações não autorizadas?",
        ],
        "PDB - 5400": [
            "Integridade do painel (corrosão, danos)?",
            "Fiação organizada e identificada?",
            "Disjuntores/fusíveis corretos?",
            "Bornes apertados?",
            "Aterramento adequado?",
            "Diagrama elétrico disponível?",
            "Limpeza interna?",
        ],
        "JB - 5500": [
            "Integridade da caixa de junção?",
            "Bornes apertados?",
            "Fiação organizada e identificada?",
            "Entradas de cabos seladas?",
            "Aterramento correto?",
            "Identificação da caixa?",
            "Limpeza interna?",
        ],
        "Cable Tray - 5600": [
            "Integridade da bandeja (sem deformações, corrosão)?",
            "Fixações seguras?",
            "Cabos organizados e amarrados?",
            "Sem cantos vivos que possam danificar cabos?",
            "Aterramento da bandeja?",
            "Identificação da rota?",
            "Capacidade de preenchimento adequada?",
        ],
        "Cables - 5700": [
            "Integridade da isolação?",
            "Identificação do cabo (TAG)?",
            "Conexões corretas e apertadas?",
            "Sem dobras ou torções excessivas?",
            "Proteção mecânica adequada?",
            "Rota do cabo conforme projeto?",
            "Certificado de material disponível?",
        ],
        "Glands & Acces. - 5800": [
            "Prensa-cabos apertados e vedados?",
            "Acessórios (terminais, conectores) corretos?",
            "Sem sinais de corrosão?",
            "Identificação do cabo na conexão?",
            "Material adequado para o ambiente?",
            "Instalação conforme norma?",
            "Quantidade verificada?",
        ],
        "Others - 5900": [
            "Condição geral do item?",
            "Função principal operacional?",
            "Conexões seguras?",
            "Identificação (TAG) visível?",
            "Documentação disponível?",
            "Acesso para manutenção?",
            "Sem danos visíveis?",
        ],
        "Tubing - 6100": [
            "Integridade do tubo (sem amassados, corrosão)?",
            "Material correto?",
            "Identificação da linha/tubo?",
            "Sem dobras excessivas?",
            "Limpeza interna?",
            "Comprimento conforme especificação?",
            "Certificado de material disponível?",
        ],
        "Fittings - 6200": [
            "Tipo e material corretos?",
            "Roscas/conexões em bom estado?",
            "Sem sinais de corrosão?",
            "Aperto adequado?",
            "Identificação do fabricante?",
            "Embalagem original (se novo)?",
            "Quantidade conforme lista?",
        ],
        "Stauff Clamp - 6300": [
            "Tipo e tamanho corretos?",
            "Fixação segura?",
            "Sem sinais de danos?",
            "Material adequado?",
            "Quantidade conforme projeto?",
            "Alinhamento do tubo/mangueira?",
            "Acesso para manutenção?",
        ],
        "Valves - 6400": [ # Válvulas de instrumentação/tubing
            "Condição geral da válvula?",
            "Operação suave (abrir/fechar)?",
            "Vedações sem vazamentos?",
            "Identificação (TAG) visível?",
            "Conexões apertadas?",
            "Material correto?",
            "Acesso para operação?",
        ],
        "Air Header - 6500": [
            "Integridade do coletor de ar?",
            "Válvulas de dreno funcionando?",
            "Manômetro funcionando?",
            "Conexões de saída seguras?",
            "Sem vazamentos de ar?",
            "Fixação segura?",
            "Identificação do coletor?",
        ],
        "Transmitters & TW - 6600": [
            "Transmissor em bom estado?",
            "Conexões elétricas e de processo seguras?",
            "Termopoço (TW) íntegro?",
            "Identificação (TAG) visível?",
            "Aterramento correto?",
            "Certificado de calibração disponível?",
            "Proteção contra intempéries?",
        ],
        "Density - 6700": [
            "Condição geral do densímetro?",
            "Conexões de processo sem vazamentos?",
            "Conexões elétricas/sinal seguras?",
            "Identificação (TAG) legível?",
            "Acesso para manutenção?",
            "Limpeza da célula de medição?",
            "Certificado de calibração disponível?",
        ],
        "BS&W - 6800": [
            "Condição geral do monitor BS&W?",
            "Conexões de processo sem vazamentos?",
            "Conexões elétricas/sinal seguras?",
            "Identificação (TAG) legível?",
            "Acesso para manutenção?",
            "Limpeza da célula de medição?",
            "Certificado de calibração disponível?",
        ],
        "Others - 6900": [
            "Condição geral do item?",
            "Função principal operacional?",
            "Conexões seguras?",
            "Identificação (TAG) visível?",
            "Documentação disponível?",
            "Acesso para manutenção?",
            "Sem danos visíveis?",
        ],
        "MCS - 7100": [
            "Integridade física do sistema?",
            "Conexões de rede seguras?",
            "Alimentação elétrica estável?",
            "Software carregado e funcionando?",
            "Identificação (TAG) visível?",
            "Acesso para manutenção?",
            "Documentação do sistema disponível?",
        ],
        "Flow Computers - 7200": [
            "Integridade física do computador de fluxo?",
            "Conexões de entrada/saída seguras?",
            "Alimentação elétrica estável?",
            "Software carregado e funcionando?",
            "Identificação (TAG) visível?",
            "Acesso para manutenção?",
            "Certificado de calibração disponível?",
        ],
        "Cabinet Fabrication - 7300": [
            "Integridade da estrutura do gabinete?",
            "Pintura/revestimento em bom estado?",
            "Portas e fechaduras funcionando?",
            "Vedação adequada contra poeira/água?",
            "Placa de identificação do gabinete?",
            "Aterramento correto?",
            "Ventilação adequada?",
        ],
        "Cabinet Material - 7400": [
            "Tipo de material conforme especificação?",
            "Sem sinais de corrosão ou danos?",
            "Dimensões conforme desenho?",
            "Certificado de material disponível?",
            "Quantidade verificada?",
            "Acabamento superficial adequado?",
            "Embalagem original (se novo)?",
        ],
        "Others - 7900": [
            "Condição geral do item?",
            "Função principal operacional?",
            "Conexões seguras?",
            "Identificação (TAG) visível?",
            "Documentação disponível?",
            "Acesso para manutenção?",
            "Sem danos visíveis?",
        ]
    }
    return templates.get(package, {"Default": ["Condição geral do equipamento?", "Identificação (TAG) visível?"]})
